[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "inner-scanner"
version = "0.1.0"
dependencies = [
    "rich>=13.0.0"
]

[tool.setuptools.packages.find]
where = ["src"]